### ISSUE TITLE
[Selection apprenant] Incohérence nombre total sur deux formations de la meme categorie

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#101]
J'ai deux formations déclarées sur la meme catégories :

![issue_incoherence_total_apprenants_01](https://user-images.githubusercontent.com/31622244/58970753-53234d00-87ba-11e9-94c8-fc0094466ab0.png)

Lorsque je vais sur la première, que je vais dans la sélection des apprenants et que je clique sur "Rechercher des apprenants" pour tous les récupérer ils m'en donne 22 alors que sur l'autre il m'en donne 50 :

![issue_incoherence_total_apprenants_02](https://user-images.githubusercontent.com/31622244/58970816-70581b80-87ba-11e9-94a2-7ab9831139a1.png)

![issue_incoherence_total_apprenants_03](https://user-images.githubusercontent.com/31622244/58970822-73eba280-87ba-11e9-8a1c-90f36eb83bdb.png)

_NB : il s'agit d'une formation qui avait déjà été déclarée avant la mise à jour du plug-in vers la version qui gère le concept de formation_

**Comment by cemu-guillaumegirard** [comment]
La purge des caches n'a rien donné

**Comment by mleconte** [comment]
Cela doit s'expliquer par la définition des jalons de ces 2 formations,. Les apprenants correspondent aux cours portant les jalons de la formations, il suffit donc qu'un jalon soit pris dans un cours non présent dans l'autre formation pour que le nombre d'apprenant diffère .
