### ISSUE TITLE
Cumul d'heures réalisées depuis le début de la formation

### ISSUE THREAD

**Issue by murielparis** [grp-attestoodle/moodle-tool_attestoodle#102]
Bonjour,

C'est une demande que j'ai déjà faite pour le compte notamment de l'IAE Caen mais ne l'ayant pas vue dans la nouvelle version mise en prod, je crée cette nouvelle issue. Peut-être existe t-elle déjà donc désolée si c'est le cas.

Le besoin est d'afficher sur les attestations générées et téléchargées mensuellement le cumul des heures réalisées depuis le début de la formation.

Ce qui donne la ligne suivante à ajouter :
"Temps d'apprentissage cumulé depuis le début de la formation et validé à la date du ... : .....h"

Merci d'avance
Et à votre disposition pour apporter des précisions sachant que cette demande est considérée par l'équipe IAE comme essentielle pour la rentrée en septembre prochain.

**Comment by mleconte** [comment]
Traité cf commit fb73115
