### ISSUE TITLE
[Gestion jalons] Gérer les modules en option

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#103]
Remontée lors de la présentation du plug-in à Angers :

**Contexte :**
L'université dispose d'espace cours contenant plusieurs options. Les apprenants choisissent une seule de ces options Ces options sont toutes les 3 présentes dans l'espace cours (différents lots d'activités en fonction des options) et seules les activités qui composent l'option choisie par l'apprenant lui sont accessible (restriction d'accès). 

**Fonctionnement actuel :**
Il est possible de définir un jalon identique pour chaque lot d'activités, par exemple 10h, et que l'apprenant ne puisse valider que celui auquel il a accès (restriction d'accès) et cela ne posera pas de problème pour les informations contenues dans les attestations (les totaux seront bons). En revanche il y aura 3 activités différentes déclarées comme jalons de 10h : le total d'heures pour la formation ne sera donc pas cohérent. 

**Besoin :**
Ajouter la possibilité de définir un jalon comme étant une "option" en fonction de l'apprenant. Par exemple déclarer que plusieurs activités sont "couplées" :
- Activité A : Jalon, 10h
- Activité B : Pas de jalon
- Activité C : Jalon, 20h
- Activité D : _couplé avec A (jalon 10h)_
- Activité E : _couplé avec A (jalon 10h)_
- Activité F : Pas de jalon

Et sur le total d'heure de la formation repérer que les activités sont "couplées" et n'en totaliser qu'une

**Comment by mleconte** [comment]
Je ne suis pas partisan de faire une telle bidouille, le plus correct est de définir plusieurs formations correspondantes aux différentes options. Il sera par la suite plus simple de présenter à chaque étudiant sont avancement, les activités qui lui reste à passer etc.
Alors que passer par des 'options' obliges à savoir qu'elles options sont applicables pour chaque apprenants !!

**Comment by dcadiou** [comment]
Je partage la remarque de Marc et ferme cette issue.
