### ISSUE TITLE
[Attestation] Fusion des activités homonymes

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#105]
**Contexte :**
Dans un cours j'ai deux activités bien distinctes mais avec des noms identiques. Les deux activités ont des jalons de valeurs différentes. Ces deux jalons peuvent être validés par un seul et même apprenant. Lorsque j'affiche le détail d'un apprenant, je vois bien les deux jalons validés :

_Double exemple avec activité 7 et activité 6_
![issue_fusion_activites_homonymes_01](https://user-images.githubusercontent.com/31622244/59270497-eabceb80-8c51-11e9-8f9f-696746787130.png)

**Comportement attendu :**
Lorsque je génère les attestations je dois avoir une ligne par activité (si regroupement  par activité sélectionné)

**Comportement observé :**
Les activités sont regroupées dans le tableau d'activité de l'attestation lorsque leur nom est identique :
![issue_fusion_activites_homonymes_02](https://user-images.githubusercontent.com/31622244/59270707-79316d00-8c52-11e9-95a6-719eea61a8d3.png)

**Complément d'information :**
Le cours dispose de deux activités avec le même nom (ci-dessous)
![issue_fusion_activites_homonymes_03](https://user-images.githubusercontent.com/31622244/59270754-9403e180-8c52-11e9-84d6-8cdea8079124.png)

Lorsque je change le nom d'une activité (ici pour l'exemple j'ai mis "activité 71"), celles-ci sont bien séparées sur l'attestation :

![issue_fusion_activites_homonymes_04](https://user-images.githubusercontent.com/31622244/59270785-a847de80-8c52-11e9-9801-bf41d3c9a867.png)

**Comment by mleconte** [comment]
ce n'est pas un **bug**, c'est **un regroupement par nom d'activité** ce n'est pas **aucun regroupement** !
