### ISSUE TITLE
[Generation en lot] Clique sur "Non" renvoie une erreur

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#106]
Lorsque je clique sur "Générer toutes les attestations" depuis le rapport global d'une formation, j'ai la question "Souhaitez-vous générer les x certificats ? Oui/Non". Si je clique sur "Non" j'ai une erreur `Un paramètre requis (trainingid) est manquant`

**Comment by mleconte** [comment]
corrigé sur develop commit 21f150f

**Comment by mleconte** [comment]
corrigé sur branch master  commit 18f7960
