### ISSUE TITLE
[Jalons] Report des temps jalons entre formations

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#110]
Il faudrait que les jalons soient reportés lorsque l'on créé une nouvelle formation à partir d'une catégorie comportant déjà une formation.

**Comment by mleconte** [comment]
Désolé mais comment faire cela lorsque la catégorie comporte plus d'une formation !!
Pour dupliquer une catégorie, il faudra passer par le plugin moodle-tool_save_attestoodle, !
https://github.com/grp-attestoodle/moodle-tool_save_attestoodle
