### ISSUE TITLE
Page rapport global de la formation

### ISSUE THREAD

**Issue by cemu-valerie** [grp-attestoodle/moodle-tool_attestoodle#115]
Bonjour,
lorsqu'on paramètre les dates du filtre pour générer les attestations qu'on génère puis consulte le détail d'une attestation à la fin il y a un bouton enregistrer. Il semble logique de valider la page en cliquant dessus pour retourner au filtre et générer l'attestation d'un autre étudiant. Mais le bouton et le retour au filtre remettent le filtre par défaut sur la période du 1/01 au 31/12, ce qui peut être ennuyeux.
Vu avec Guillaume, mais à signaler.
Merci,
Valérie

**Comment by mleconte** [comment]
Le bouton 'Enregistrer' est associé au formulaire de personnalisation d'attestation pour 1 apprenant.
Le bouton Enregistrer pourra être mis dans la panneau de personnalisation, et les dates  devraient à termes être enregistrées en session.

**Comment by mleconte** [comment]
Cette issue est redondante avec l'issue #100
