### ISSUE TITLE
Pas d'apprenants inscrits

### ISSUE THREAD

**Issue by Roussxx** [grp-attestoodle/moodle-tool_attestoodle#124]
Bonjour,
Excusez mon côté débutant, je découvre moodle et attestoodle...
J'ai installé le plugin, défini les catégories et cours du parcours de formation, ainsi que les jalons mais je ne trouve pas le moyen d'inscrire les apprenants. J'ai un message _"Aucun apprenant présent dans un cours avec suivi d'achèvement à partir de la catégorie associée à cette formation "__ pourtant les cours comportent des élèves inscrits et les paramètres d'achèvement de cours ont été définis dans Moodle.
Merci de votre aide

**Comment by mleconte** [comment]
Bonjour
Pour définir les apprenants d'une formation vous devez vous rendre sur l'écran "paramètres de la formation"
![bas_ecran](https://user-images.githubusercontent.com/26385729/65667045-364ba780-e03f-11e9-8094-0f4ae29c8c1d.png)
Si le temps total de la formation est supérieur à 0, c'est que vos jalons sont biens enregistré et que vous pouvez alors cliquer sur le bouton [Sélectionner les apprenants] pour choisir les élèves qui suivent la formation.
La liste d'élève est composé des **élèves inscrit à au moins un cours portant un jalon** de cette formation.
Pour optimiser les traitements l'ensemble des élèves de la catégorie n'est plus systématiquement inscrit, les formations sont définis dans une catégorie mais elles peuvent être composées de cours situés dans d'autres catégorie.
