### ISSUE TITLE
Le cumul  depuis le début de la formation est parfois incohérent avec le calcul sur une période donnée

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#135]
En production, un service de scolarité s'est plaint d'avoir, sur l'attestation d'une étudiante, des valeurs incohérentes entre cumul depuis le début de la formation et total de la période choisie. Dans ce cas précis la période choisie était : 17/9/2019 - 31/1/2020. Avec cette période, cumul  depuis le début de la formation et total sur la période devrait être identiques. Ce qui n'est pas le cas, du moins pour cette étudiante.

- cumul annuel : 187h
- total période : 215h

![image](https://user-images.githubusercontent.com/25685520/74825820-d8c83800-530a-11ea-9adb-ea2f19ee2bc0.png)

(in english : in some situations, on certificates, the annual summation (new) may differs from selected time interval total, even if the selected time interval is set to cover the same time interval as the annual summation)

**Comment by dcadiou** [comment]
Quand on liste tous les jalons validés par cette étudiantes, on constate qu'il y en a 4 de 7h, **validés le 31 janvier (dernier jour de la période)**. Cela représente 4*7 = 28h, c'est-à-dire justement le différentiel observé (215-187).

Si on regénère l'attestation avec une période qui s'étend jusqu'au 1er février 2020, les 2 chiffres s'alignent à 215h.

Le nouveau cumul annuel ne semble donc pas utiliser les mêmes règles d'inclusion ou d'exclusion des jours frontières d'une période.

L'observation réalisée l'a été pour le jour de fin. Je n'ai pas vérifié si nous avions le même soucis sur le jour de début de période.

Pour info, j'ai utilisé la requête suivante pour contrôler en base :
```sql
select FROM_UNIXTIME(cmc.timemodified) as quand,
	c.shortname as cours,
	j.creditedtime as minutes,
	TIME_FORMAT(SEC_TO_TIME(j.creditedtime * 60), '%H:%i:%s') as credited
from mdl_user u 
	join mdl_course_modules_completion cmc on cmc.userid  = u.id
	left join mdl_tool_attestoodle_milestone j on j.moduleid = cmc.coursemoduleid 
	join mdl_course_modules cm on cm.id = cmc.coursemoduleid 
	join mdl_course c on c.id = cm.course 
where u.id = xxxx -- id de l'étudiante
	and cmc.timemodified > UNIX_TIMESTAMP('2019-09-17') 
	and cmc.timemodified < UNIX_TIMESTAMP('2020-02-01') 
	and j.creditedtime is not null
order by quand;
```

**Comment by mleconte** [comment]
La notion de cumul annuel n'existe pas, il existe uniquement un cumul depuis le début de la formation.

**Comment by mleconte** [comment]
Corrigé avec le commit dbbc9a0 (version 1.8.4). La journée complète de la fin de période est désormais prise en compte, le début de période **n'est pas** et **ne doit pas** être pris en compte pour l'obtention du cumul depuis le début de la formation .

**Comment by dcadiou** [comment]
Merci pour la correction.
