### ISSUE TITLE
Nombre d'apprenant : 0

### ISSUE THREAD

**Issue by dahu37** [grp-attestoodle/moodle-tool_attestoodle#139]
Bonjour,

Avant tout je vous remercie pour votre travail, auquel je porte un intérêt particulier, les fonctions proposées revêtant un véritable intérêt dans le cadre du suivi pédagogique.

J'ai le même problème que #124 , la liste d'élève reste vide alors que j'ai bien des élèves inscrits aux cours portant jalons de la formation, et qu'une durée apparait bien pour "temps total de formation".

En pratique, quand je clique sur sur "sélectionner les apprenants", les 3 boutons (rechercher apprenant, critère inscription et critère formation) ne produisent aucun effet et le nombre d'apprenant reste à 0.

Faut-il que les apprenants appartiennent à un rôle spécifique ?

**Comment by mleconte** [comment]
Bonjour
merci pour l'intérêt que vous portez à ce plugin.
En effet les apprenants doivent être inscrits dans les cours avec le rôle "étudiants", ce dernier étant déterminé avec la requête suivante 
                                get_record('role', array('shortname' => 'student'), "id");
C'est à dire, comme le rôle dont le shortname = 'student'.

**Comment by dahu37** [comment]
Merci beaucoup ça a l'air de fonctionner !
