### ISSUE TITLE
Did you remember to make the first column something unique in your call to get_records

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#141]
Bonjour Marc ;-)

En production nous avons été dans l'impossibilité temporaire de sortir les attestations d'une formation donnée (les autres fonctionnaient) à cause d'un warning qui se produit chaque fois qu'on essait d'ouvrir le 'rapport global de la formation' (URL du cas présent : https://webapp/moodle/admin/tool/attestoodle/index.php?typepage=learners&categoryid=8860&trainingid=16)

Ca s'est produit avec la version d'Attestoodle actuellement en prod (commit db2ac9050b22d2749c7e7a78c42d0e30390355c2, release v1.8.3).

J'ai pu reproduire le même phénomène dans une infra virtuelle de test, avec les données de prod et la dernière version d'attestoodle : 9dbfa871ac986b825d02b7667e66135c665ac46d

Avec nos réglages courants de debug en production, nous récupérions une page index.php vide. Une fois les options de debug plus verbeuses activée (pour l'admin), on a pu voir : 
```
Did you remember to make the first column something unique in your call to get_records? Duplicate value '2020-5-1' found in column 'begindate'.

    line 1256 of /lib/dml/mysqli_native_moodle_database.php: call to debugging()
    line 193 of /admin/tool/attestoodle/classes/utils/plugins_accessor.php: call to mysqli_native_moodle_database->get_records_sql()
    line 156 of /admin/tool/attestoodle/index.php: call to tool_attestoodle\utils\plugins_accessor::get_interval()
```
On trouve aussi cette notice php dans le` /var/log/apache2/error.log`

Effectivement juste avant la ligne 193 de `classes/utils/plugins_accessor.php`, on trouve une requête SQL. Après remplacement des paramètres par leur valeur, on a :

```sql
select l.begindate, l.enddate
                  from mdl_tool_attestoodle_certif_log c
                  join mdl_tool_attestoodle_launch_log l on c.launchid = l.id
                 where trainingid = 16
              order by enddate desc
;
```

ce qui retourne, dans notre cas :

```
begindate |enddate   |
----------|----------|
2020-5-1  |2020-5-31 |
2020-5-1  |2020-5-31 |
2020-5-1  |2020-5-31 |
2020-5-1  |2020-5-31 |
2020-5-1  |2020-5-31 |
2020-5-1  |2020-5-31 |
2020-5-1  |2020-5-31 |
2020-5-1  |2020-5-31 |
2020-5-1  |2020-5-31 |
2020-5-1  |2020-5-31 |
2020-5-1  |2020-5-31 |
2020-4-1  |2020-4-30 |
2020-4-1  |2020-4-30 |
...
```

On voit que la première colonne contient plusieurs fois les mêmes valeurs, par exemple '2020-5-1'.

Or dans l'entête de la sous-fonction qui exécute cette requête (`get_records_sql()` dans `lib/dml/mysqli_native_moodle_database.php`), on peut lire, entre autres : 

```php
@param string $sql the SQL select query to execute. The first column of this SELECT statement
*   must be a unique value (usually the 'id' field), as it will be used as the key of the
*   returned array.
```
 
Donc quand on appelle cette fonction, la requête doit retourner une première colonne, qui sera utilisée comme clé pour un tableau php, donc avec des valeurs uniques. Ce n'est pas toujours le cas de la présente requête.

(english summary : a php notice is sometime generated when visiting the training global report. One of the executed query which is expected to return rows with unique value in the first column, may returns non unique values in it)

**Comment by dcadiou** [comment]
On peut facilement éviter le warning en ajoutant un champ unique à la requête, comme avec ce patch : 
[186614.patch.zip](https://github.com/grp-attestoodle/moodle-tool_attestoodle/files/4897450/186614.patch.zip)

Je m'interroge cependant sur la logique de la fonction `get_interval()`. Apparamment avec la variable `$first`, seul le premier enregistrement de la requête est traité. Dans ce cas pourquoi ne pas requêter que celui-là ? Mais ne voulons-nous vraiment que ce premier enregistrement ?

**Comment by mleconte** [comment]
Bonjour
le patch que tu proposes correspond à ce que je pensai mettre en place pour corriger le bug.
En fait uniquement le premier enregistrement est intéressant, il correspond à l'intervalle le plus récent, avec le sous plugin task attestoodle on ne passe plus par ce code mais on récupère la planification créée.

**Comment by mleconte** [comment]
J'ai appliqué ton patch commit  949436b
Je ferai une release et une mise à jours Moodle en septembre, après les tests de compatibilité Moodle 3.9
