### ISSUE TITLE
Failed update from Moodle 3.5 to Moodle 3.9 : new fields cannot be added

### ISSUE THREAD

**Issue by Gael-Mifsud** [grp-attestoodle/moodle-tool_attestoodle#147]
Hello,
When we tried to update our Moodle 3.5 to Moodle 3.9, we also tried to update attestoodle.
But we encountered the error : new fields cannot be added. Because of lack of default value as you can see in the attached screenshot.

What can be done ?

Thanks

![Screenshot 2021-06-23-attestoodle](https://user-images.githubusercontent.com/2854045/123124553-116caa00-d448-11eb-9a10-ca6b2cec014e.png)

**Comment by mleconte** [comment]
Sorry but the easiest way would be to uninstall Attestoodle and then install the new version.

**Comment by Gael-Mifsud** [comment]
Thank you for your answer.
We understand there is nothing more to do with this Moodle.

But we have some other Moodles to update. Can we do something for them before the update ?
For example, is it possible to add a default value in the /db/upgrade.php of attestoodle ?

Thanks.

**Comment by mleconte** [comment]
You can put this version of Attestoodle, the startdate field is added as nullable
[moodle-tool_attestoodle-master.zip](https://github.com/grp-attestoodle/moodle-tool_attestoodle/files/6709152/moodle-tool_attestoodle-master.zip)
This should correct the problem with the update.

**Comment by Gael-Mifsud** [comment]
Thank you very much.
We used the master you provided in your last message, and it worked !

I can close this ticket, I think.
