### ISSUE TITLE
Navigation pas intuitive

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#23]
[Copied from initial repository]
J'ai mis Attestoodle en test chez nous et on m'a demandé tout de suite "Comment puis-je accéder aux paramétrages des jalons ?". En effet il faut d'abord aller dans "suivi des étudiants" avant de trouver ce paramétrage, pas logique.

**Comment by mleconte** [comment]
La navigation à été revue, ce problème est-il toujours à prendre en considération ?

**Comment by cemu-guillaumegirard** [comment]
Invalide.
