### ISSUE TITLE
Mapping role - permission par défaut

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#48]
Dans l'état actuel du plugin (commit ), il n'y a que le rôle gestionnaire qui a des droits sur attestoodle.
Un enseignant, ne peut rien faire.

Je pense, à défaut d'avoir une réflexion plus construite plus tard, qu'il faudrait définir un certain nombre de permissions attestoodle pour le rôle enseignant. Sinon les premiers testeurs, risquent d'être trop rapidement confronté à des problèmes de droits.

**Comment by mleconte** [comment]
les rôles sont liés aux contextes, le rôle enseignant n'a de porté que dans un contexte de cours.
Il faudrait un plugin d'activité ou de bloc pour associer une partie d'attestoodle avec les enseignants
