### ISSUE TITLE
Problème(s) de définition des permissions

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#49]
Je viens de modifier un des rôles propriétaires, 'personnel administratif' sur notre plateforme en prod, pour qu'un personnel administratif puisse voir les stats des étudiants et générer des attestations.

Sur la base du nom des permissions disponibles, j'ai donc configuré mes rôles comme suit : 
![image](https://user-images.githubusercontent.com/25685520/51985317-e01d6900-249d-11e9-8299-6fb503ebb6d2.png)

Hors quand je me connecte en tant qu'une personne qui a ce rôle 'personnel administratif', je ne vois même pas l'icone Attestoodle. Je n'ai donc accès à rien.

**Comment by dcadiou** [comment]
Guillaume vient de me dire qu'il faut la permission '_Ajouter/Supprimer une formation_' : **tool/attestoodle:managetraining** pour voir l'icône attestoodle dans l'administration de la catégorie.

J'ai ajouté cette permission et effectivement maintenant un personnel administratif accède au plugin. En revanche, il peut aussi modifier trop de choses, par exemple retirer cette catégorie de la liste des formations.

**Comment by mleconte** [comment]
il faudra découpler ce droit, comme je l'avais signalé il n'existe pas d'écran de consultation, aussi je pense qu'il faudra réaliser un premier écran de consultation qui offrirait aux ayant droit de passer en mode modification/suppression de formation.

**Comment by dcadiou** [comment]
Il faudrait peut être ajouter une permission 'accéder au plugin'.

Dans la page de gestion de la formation, par exemple, on pourrait aussi laisser tout ou partie des éléments actuels affichés, mais en désactiver certains (not enabled) pour les gens qui n'ont pas les bonnes permissions.
 
Par exemple je trouverai bien que mon personnel administratif puisse avoir confirmation, après avoir cliqué sur le lien attestoodle, que la catégorie a bien été déclarée comme formation et quel nom lui a été donnée.

**Comment by dcadiou** [comment]
Salut Marc.

Tout à fait d'accord.

On pourrait, à terme, avoir une page d'accueil en arrivant dans le plugin, qui précise, par exemple : 

- cette catégorie est considérée formation par Attestoodle
- elle inclue x jalons définis dans y cours
- z étudiants sont inscrits à au moins un des cours

puis les liens (actif ou non suivant les permissions) : 
- modifier cette formation
- gérer les jalons
- rapport global de la formation

**Comment by mleconte** [comment]
En fait je pensai, mettre en place quelque chose de plus Moodle (Activer le mode édition)

**Comment by dcadiou** [comment]
La proposition que j'ai faite avait juste pour ambition de lister des points à ne pas oublier. Bien sur il faut rester dans l'ergonomie Moodle habituelle.
Par contre il faut considérer que modifier la formation, n'est pas la même chose que gérer les jalons ni accéder aux stats des étudiants. 
Un "mode édition" au niveau de la formation me parait trop binaire s'il n'y a que ça.

**Comment by mleconte** [comment]
clôturée car redondante avec issue #130
