### ISSUE TITLE
[Modèle d'attestation] Gros tableau d'activités et informations dans le pied de page

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#51]
**Contexte :** 
Définition d'un template
Ajout d'une information dans le "pied de page" ("Signature de l'apprenant" par exemple)
Dans les règles de saut de page, mettre "Informations après le tableau" à "Sur toutes les pages"

**Comportement attendu :** 
Si le "tableau des activités" est gros (deux pages), ladite information en pied de page devrait rester au même endroit sur toutes les pages et le tableau ne devrait pas prendre toute la place

**Comportement observé :**
Le "tableau des activités" descend jusqu'en bas de la page et l'information en pied de page n'est pas affichée correctement sur la première page

Voir fichier ci-dessous :
[preview.pdf](https://github.com/grp-attestoodle/attestoodle/files/2837213/preview.pdf)
***
(in english)
**Context:** 
Defining a template. 
Added "footer" information (learner signature for the example). 
In page break rules, set **Informations after table** to **On all pages** 

**Expected behavior:** 
If the "table of activites" is big (two page), the so called "footer information" should be on the same spot in every pages and the table shouldn't take all the space.

**Observed behavior:**
The "table of activites" is going all the way down the first page and the "footer information" is not displayed properly in the first page. 

See file bellow
[preview.pdf](https://github.com/grp-attestoodle/attestoodle/files/2837213/preview.pdf)

**Comment by mleconte** [comment]
Ceci n'est pas un Bug, regarde sur le complément de la doc utilisateur, il est nécessaire de définir des littéraux pour conserver une marge en bas de page.

**Comment by cemu-guillaumegirard** [comment]
C'est ce que j'ai fait si je ne m'abuse : j'ai déclaré le littéral "Signature de l'apprenant" à y = 230 (testé aussi jusqu'à y = 280). J'ai également essayé avec deux littéraux (mêmes valeurs en y) mais rien n'y fait. Y a un truc que j'ai mal fait ?
Doc :

> 
On peut préserver l’espace sous le tableau en plaçant des littéraux sous le tableau, le débordement du tableau sera autoriser tant que les éléments sous le tableau reste sur la page. Ainsi, avec un élément à 35 mm du bas de la page et un élément sur la dernière ligne de la page, nous somme assuré de préserver une marge de 35mm.

Je ne suis pas sûr d'avoir compris "et un élément sur la dernière ligne de la page"...

------ 

English :
I think that's what I did: I declared the litteral "Signature de l'apprenant" with y = 230 (tested until y = 280). I added two litteral (same y value) but nothing does the trick. What did I miss?
Doc:

> We can preserve the space under the table by placing two litterals bellow the table [...]. With an element 35mm overhead the page bottom and an element on the last line of the page, we'll have a 35mm margin bottom.

I'm not sure that I understood "and an element on the last line of the page" tho...
