### ISSUE TITLE
[Gestion des jalons] Ajouter un filtre "Suivi d'achèvement activé"

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#52]
Sur la page de gestion des jalons, ajouter un filtre "Suivi d'achèvement activé" pour ne faire apparaitre que les activités qui ont un suivi d'achèvement. Le filtre devrait être par défaut sur "Ne pas afficher" pour empêcher l'utiliser de mettre un jalon sur une activité que les apprenants ne peuvent pas valider.
***
(in english)
On the "Manage milestones" page, add a filter "Completion enabled" to display only the activities that have a completion setting. This filter should be set to "No display" by default to avoid the user to set a milestone on an activity that learners cannot complete.

**Comment by cemu-guillaumegirard** [comment]
Issue probablement devenue invalide suite au changement de fonctionnement

**Comment by mleconte** [comment]
Effectivement issue invalid, lors des optimisation des temps de traitements, uniquement les activités avec suivi d'achèvement sont sélectionnés dans la liste des jalons potentiels.
