### ISSUE TITLE
[Manage milestones] Add a title to the "warning no completion" icon

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#53]
On the **Manage milestones** page there is an icon before the activities' names when they don't have a completion set. This icon is not explicit and a _title_ attribute should be added to the HTML output saying something like "Warning! This activity can not be completed by the learners and should not contain a milestone!"

**Comment by cemu-guillaumegirard** [comment]
Sans doute invalide suite à changement de fonctionnement du formulaire

**Comment by mleconte** [comment]
Nous ne sélectionnons plus d'activités sans suivi d'achèvement.
