### ISSUE TITLE
[Rapport détaillé] Ajouter le total d'heures validées

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#54]
Sur la page de détails d'un apprenant devrait apparaître le nombre total d'heures validées par l'apprenant sur la période sélectionnée
***
(in english) On the page detailing the milestones validated by a single learner, somewhere should appear the total amount of milestones validated on the specified period (new line at the bottom of the table for example ?)

**Comment by mleconte** [comment]
corrigé par commit 1e2a3e8
