### ISSUE TITLE
[Gestion des jalons] Appuuer sur la touche "Entrée" ne valide pas le formulaire

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#56]
**Contexte :** 
Page de gestion des jalons, appuyer sur la touche "Entrée" lorsqu'on est dans un champ

**Comportement attendu :**
Le formulaire est validé et les jalons sont mis à jour et sauvegardés.

**Comportement observé :**
La page se raffraichit mais les jalons ne sont pas validés.
***
(in english)
**Context**: 
Manage milestones, pressing "Enter" in a field. 

**Expected behavior:**
The form is validated and the milestones updated are saved.

**Observed behavior:**
The page reload but the form is not validated

**Comment by mleconte** [comment]
in french or not here

**Comment by cemu-guillaumegirard** [comment]
In english or not a plugin Moodle.

**Comment by mleconte** [comment]
Ce n'est qu'une remarque d'un modérateur le plugin est à destination des universités Françaises
Si cela t'amuses de rédiger en Anglais, tu perd ton temps, il vaudrait mieux que tu corriges directement.
je ne traiterai aucune issue rédigé en anglais !!
 Il est largement plus important de s'occuper de l'API Privacy.

**Comment by cemu-guillaumegirard** [comment]
Certes pour l'API Privacy. Cela dit le bug ne semble, bizarrement, pas avoir été corrigé juste en signifiant dans les commentaires de l'issue qu'il était écrit en anglais. 
Je ré-ouvre.

**Comment by mleconte** [comment]
Je remarque que guillaume n'a pas corrigé ce qu'il mentionne comme 'minor bug', et qui à été codé par lui.
En ce qui me concerne cela ne constitue pas un bug
