### ISSUE TITLE
[Toutes les pages] Changer de langage redirige vers une mauvaise URL

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#58]
Quand on change le langage de Moodle (dans le header), la page doit se raffraichir sur elle-même en ajoutant un paramètre "lang". Quand on change depuis n'importe quelle page d'Attestoodle l'URL est mauvaise; 

Exemple :
http://localhost:180/moodle/admin/tool/attestoodle/index.php
redirige vers
http://localhost:180/moodle/var/www/html/moodle/admin/tool/attestoodle/index.php?lang=fr

Je pense que c'est un problème au niveau des appels à `$PAGE->set_url(...);`
***
(in english)
When switching language from one to another the page should reload to itself with the new parameter "lang". When switching on any page of attestoodle it redirect to a bad URL.

Example:
http://localhost:180/moodle/admin/tool/attestoodle/index.php
redirect to 
http://localhost:180/moodle/var/www/html/moodle/admin/tool/attestoodle/index.php?lang=fr

I think the problem comes from the `$PAGE->set_url(...);` calls

**Comment by mleconte** [comment]
corrigé par le commit 279dd0f
