### ISSUE TITLE
[Meta] Problèmes de "coding style" JavaScript

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#59]
Source : moodle eslint prechecker:

> admin/tool/attestoodle/classes/generated/scriptajax.js
    (1) Comments should not begin with a lowercase character (capitalized-comments)
    (1) Missing JSDoc for parameter 'e'. (valid-jsdoc)
    (1) Missing JSDoc for parameter 'args'. (valid-jsdoc)
    (5) Identifier 'ajax_certif_generate' is not in camel case. (camelcase)
    (5) 'ajax_certif_generate' is defined but never used. (no-unused-vars)
    (19) Extra space after key 'sesskey'. (key-spacing)
    (19) Extra space after key 'launchid'. (key-spacing)
    (20) Extra space after key 'trainingid'. (key-spacing)
    (21) Extra space after key 'categoryid'. (key-spacing)
    (23) Unexpected space before function parentheses. (space-before-function-paren)
    (25) 'displayBar' is not defined. (no-undef)
    (27) Unexpected space before function parentheses. (space-before-function-paren)
    (27) 'response' is defined but never used. (no-unused-vars)
    (28) Unexpected alert. (no-alert)

Voir https://moodle.org/plugins/pluginversion.php?id=18790&smurf=html#js pour les détails

**Comment by cemu-guillaumegirard** [comment]
Updated as of v1.3.1 publication:

> Javascript coding style problems
> 
> (2 errors, 11 warnings)
> 
> This section shows the coding style problems detected in the code by eslint [More info]
> 
> admin/tool/attestoodle/classes/generated/scriptajax.js
>     (1) Comments should not begin with a lowercase character (capitalized-comments)
>     (1) Missing JSDoc for parameter 'args'. (valid-jsdoc)
>     (1) Missing JSDoc for parameter 'e'. (valid-jsdoc)
>     (5) 'ajax_certif_generate' is defined but never used. (no-unused-vars)
>     (5) Identifier 'ajax_certif_generate' is not in camel case. (camelcase)
>     (19) Extra space after key 'sesskey'. (key-spacing)
>     (19) Extra space after key 'launchid'. (key-spacing)
>     (20) Extra space after key 'trainingid'. (key-spacing)
>     (21) Extra space after key 'categoryid'. (key-spacing)
>     (23) Unexpected space before function parentheses. (space-before-function-paren)
>     (25) 'displayBar' is not defined. (no-undef)
>     (27) Unexpected space before function parentheses. (space-before-function-paren)
>     (28) Unexpected alert. (no-alert)

See https://moodle.org/plugins/pluginversion.php?id=19265&smurf=html#js for details

**Comment by mleconte** [comment]
Ce "warning" n'est pas à prendre en compte, on ne pourra jamais supprimer :
  'ajax_certif_generate' is defined but never used. (no-unused-vars)
Car cette méthode est appelée dans un autre source !!

Pareil pour : 
'displayBar' is not defined. (no-undef)
Car ce composant est définie dans l'autre source.
