### ISSUE TITLE
Compatibility with Moodle 3.6

### ISSUE THREAD

**Issue by germanvaleroelizondo** [grp-attestoodle/moodle-tool_attestoodle#60]
Is this plugin compatible with Moodle 3.6 ?
Stats page (https://moodle.org/plugins/stats.php?plugin=tool_attestoodle ) only shows one Moodle 3.6 site user.

**Comment by mleconte** [comment]
Sorry for the late answer, but yes, the plugin is compatible with moodle 3.6.3
I am currently testing under this version, the implementation of the Privacy API
