### ISSUE TITLE
Problème de performances

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#61]
Des problèmes de performances sont évoqués par Johnatan dans le mail joint : 

[mail_johnatan_20190212.pdf](https://github.com/grp-attestoodle/moodle-tool_attestoodle/files/2856303/mail_johnatan_20190212.pdf)

Est-ce que cette issue est à rapprocher des issues #14 et #24 ?

Note : Le deuxième problème cité dans le mail fait l'objet d'un autre ticket.

_(in english : the attached mail is dealing with performances problems. Is thoses problems to be linked with #14 and #24 issues ?)_

**Comment by mleconte** [comment]
corrigé par d51e439
