### ISSUE TITLE
Page blanche dans la gestion des jalons

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#62]
Ci joints un mail de Johnatan qui décrit l'affichage d'une page blanche lors de la consultation des jalons.

Le mail : 
[mail_johnatan_20190212.pdf](https://github.com/grp-attestoodle/moodle-tool_attestoodle/files/2856337/mail_johnatan_20190212.pdf)

Note: le problème de performance fait l'objet d'un autre ticket.

(in english: The attached mail describe white pages display when trying to managed milestones)

**Comment by cemu-guillaumegirard** [comment]
Effectivement 10 secondes pour les formations ça me parait un peu long...

Pour essayer de baliser le problème, est-ce que tu pourrais me donner tous les droits Attestoodle sur la plateforme de prod avec mon id Univ-lemans ? J'ai accès à la plateforme mais j'ai juste le message qui me dit que je ne peux pas accéder à la fonctionnalité.

Si pas possible :
- Est-ce que la page charge un certain temps et s'arrête ? Ou bien elle plante presque directement ?
- Est-ce que tu peux accéder à d'autres fonctionnalités ? (déclaration d'une formation, paramètre de la formation, modèles d'attestation notamment)
- Il y a à peu près combien de cours dans la formation que tu veux administrer ? Et combien d'activité en tout ? (grosso merdo)
-----
English: Asking for details about the bug context (big training? do other features work?...)

**Comment by jonathanjoegit** [comment]
Pour info : 
La page charge et s'arrête au bout de plusieurs 10e de secondes sur une erreur 500
Le souci est arrivé sur une catégorie avec 8 cours actifs et 1510 activités (infos de Marc)
Je n'ai pas de message d'erreur dans les logs à priori
Tu verras @cemu-guillaumegirard tout rame pas mal...

**Comment by mleconte** [comment]
Corrigé par commit d51e439
