### ISSUE TITLE
[Modèle] Traduction des types d'activités

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#63]
**Contexte :**
Dans les paramètres d'une formation, définir un des regroupements (niveau 1 ou niveau 2) à _Type d'activité_ et enregistrer.

**Comportement attendu :**
- L'aperçu du modèle affiche les traductions des types d'activité. 
- Les attestations générées pour cette formation contiennent les traductions des types d'activités. 

**Comportement observé :**
Ni l'aperçu ni les attestations générées ne contiennent les traductions des types d'activités mais les identifiants de ces types d'activités (assign, quiz, ...)

***

**English:** when defining _activity type_ within a template for a training, neither the preview nor the generated certificates contains the translation of the types but the type identifier instead.

**Comment by mleconte** [comment]
Corrigé par le commit 2268d81
