### ISSUE TITLE
Undefined property (or index) in in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#7]
Après avoir cliqué sur [enregistrer] lors de la création d'un nouveau modèle d'attestation, j'ai eu une longue série de messages d'erreur :

> Notice: Undefined property: stdClass::$text1FontFamily in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 168
> 
> Notice: Undefined property: stdClass::$text1FontSize in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 169
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 374
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 376
> 
> Notice: Undefined property: stdClass::$text2FontFamily in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 173
> 
> Notice: Undefined property: stdClass::$text2FontSize in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 174
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 374
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 376
> 
> Notice: Undefined property: stdClass::$text3FontFamily in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 178
> 
> Notice: Undefined property: stdClass::$text3FontSize in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 179
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 374
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 376
> 
> Notice: Undefined property: stdClass::$text4FontFamily in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 183
> 
> Notice: Undefined property: stdClass::$text4FontSize in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 184
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 374
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 376
> 
> Notice: Undefined property: stdClass::$text5FontFamily in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 188
> 
> Notice: Undefined property: stdClass::$text5FontSize in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 189
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 374
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 376
> 
> Notice: Undefined property: stdClass::$pagenumberFontFamily in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 197
> 
> Notice: Undefined property: stdClass::$pagenumberFontSize in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 198
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 374
> 
> Notice: Undefined index: in /media/vdata_ecampus-pp/www/moodle/admin/tool/attestoodle/classes/gabarit/sitecertificate.php on line 376

Ce problème est apparu sur le serveur de préprod de Caen avec attestoodle en version : **077bc94**

Si je clique sur "continuer", une notification me dit que le nouveau modèle a été enregistré. De fait il apparait dans la liste.
En revanche, si je clique sur l'icone (oeil) pour en voir un aperçu, j'ai un pdf de 8 pages qui ne contiennent que l'image d'arrière plan.

**Comment by dcadiou** [comment]
J'ai entré les divers coordonées X et Y en pixels. Ce n'est peut-être pas ce qu'il fallait faire...

Je l'ai refait en mm, et là plus de message d'erreur et apparition du contenu au dessus de l'image de fond. 

Le bug semble donc lié à des valeurs trop grandes.

**Comment by dcadiou** [comment]
Dans un mail d'aujourd'hui, Marc indique qu'il n'arrive pas à reproduire le bug.

**Comment by cemu-guillaumegirard** [comment]
Ne pas pas être reproduit tant que l'issue #31 n'est pas résolue.

**Comment by cemu-guillaumegirard** [comment]
Issue #31 corrigé. Testé mais non reproduit.
@dcadiou peux-tu retester ce bug ? Si tu ne reproduis pas non plus tu peux clore l'issue
