### ISSUE TITLE
Select learners : Out of range value for column 'selected' at row 1

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#86]
Dans la page de gestion d'une formation, quand on clic sur le bouton [**Select learners**], la page admin/tool/attestoodle/classes/training/select_learners.php?categoryid=15890&trainingid=2 s'ouvre avec le message d'erreur : 
Out of range value for column 'selected' at row 1

![image](https://user-images.githubusercontent.com/25685520/58461109-312d2900-812f-11e9-8ad3-2ea602d42975.png)

Ce bug est apparu depuis le passage de mon infra de test local (sous docker, mais avec les données récentes de prod ecampus à Caen) du commit 05c4545 (version 2019010901) au dernier commit sur master, e075977 (version 2019043001)

_(in english : This issue can be seen when clicking on the button [Select learners] in the training management page, with the commit e075977)_

**Comment by dcadiou** [comment]
En comparant avec le MCD décrit dans le wiki (https://github.com/grp-attestoodle/moodle-tool_attestoodle/wiki/tables), mais aussi `install.xml` et `upgrade.php`, il manque dans ma base les tables suivantes :

- mdl_tool_attestoodle_user_style
- mdl_tool_attestoodle_learner
- mdl_tool_attestoodle_tmp

Lors de la mise à jour (via un `git pull origin master` dans le dossier attestoodle), la mise à jour de la base de données s'est bien effectuée. On en trouve la trace notamment dans la table `mdl_tool-attestoodle_training` qui est passé de 3 champs à une petite dizaine.

Tout se passe comme si l'instruction `$dbman->create_table` dans `upgrade.php` ne fonctionnait pas.

Reste à savoir si cette situation découle d'une spécificité de notre plateforme ou d'un problème plus générique.

**Comment by mleconte** [comment]
bug corrigé par le commit e075977 , la colonne selected était mal initialisée.

**Comment by dcadiou** [comment]
Je ne suis pas sur que le bug soit corrigé par le commit e075977 ou en tous cas pas en totalité.

Je viens de réessayer une install d'Attestoodle sur une autre infra docker avec un moodle neuf (MOODLE_35_STABLE). 
J'ai fait 

```
git clone https://github.com/grp-attestoodle/moodle-tool_attestoodle.git attestoodle
cd attestoodle/
git checkout 05c4545
```
J'ai visité Moodle (mise à jour de la BD), puis j'ai regardé la liste des tables attestoodle en base.
Puis j'ai fait 
```
git checkout master
```
J'ai visité Moodle (mise à jour de la BD), puis j'ai regardé de nouveau.

J'obtiens :  
![image](https://user-images.githubusercontent.com/25685520/58467410-e2d25700-813b-11e9-896a-8486f867c1ec.png)

Cette fois j'ai bien 2 des 3 tables qui apparaissent. Par contre, il manque la table **tmp**.

**Comment by mleconte** [comment]
la correction concerne le premier bug de ce fil, ce qui est ensuite présenté (problème sur les tables) est un autre problème que je ne rencontre pas en passant par l'installation normale d'un plugin.

**Comment by dcadiou** [comment]
Marc, comme décrit dans le 1er commentaire, ce (ou ces) bug(s) est(sont) apparu(s) avec le commit e075977, donc qui inclut déjà le fix dont tu parles.

**Comment by mleconte** [comment]
au temps pour moi en ce qui concerne le numéro de commit il s'agit du 7c37da3 sur la branche develop

**Comment by dcadiou** [comment]
Je continue les investigations. Là j'essaie avec un moodle dockerisé, neuf puis initialisé (pas encore mais c'est en cours) avec quelques étudiants, pour voir si [select learners] fonctionne sur la branche master, sans la table tmp.
Je pense qu'entre autres problème, il y a un problème d'upgrade. C'est donc un peu chiant à debugger car il faut faire la montée de versions et regarder comment l'upgrade.php s'exécute.
Si on veut reproduire l'opération, il faut revenir à la 1ere version, donc désinstaller/réinstaller, puis upgrade de nouveau.
J'ai programmé (information utilisateurs comprise) une mise en jour en prod demain matin, ça me laisse donc une après midi pour comprendre et corriger si nécessaire. Je suis embêté par le fait que le comportement n'est pas le même avec les données de prod. 
Il faudra donc probablement que j'analyse le comportement, y-compris avec les données de prod.

**Comment by dcadiou** [comment]
Bon finalement il y avait 3 problèmes.

**Problème 1**
La table `mdl_tool_attestoodle_tmp` manque à cause d'un bug dans `db/upgrade.php` (voir issue #89 https://github.com/grp-attestoodle/moodle-tool_attestoodle/issues/89)

**Problème 2**
Les 2 autres tables étaient absentes à cause d'une mauvaise initialisation de l'infrastructure de test : extraction d'une archive de BDD en .tar dans le dossier de travail mysql /var/lib/mysql du serveur de base de données, lequel contenait au préalable déja une base avec les 2 tables en question. Contrairement à ce que j'imaginais, l'extraction n'écrase pas le dossier en entier, mais uniquement les fichiers qu'elle doit remplacer. En conséquence les anciens fichiers qui ne sont pas écrasés, demeurent. C'était visiblement le cas de ceux des 2 tables.

Indépendamment de ma mauvaise initialisation, ce problème n'aurait pas dû se produire car dans `upgrade.php`, on commence par supprimer une table si elle existe déjà : 
![image](https://user-images.githubusercontent.com/25685520/58495588-2f3b8800-8178-11e9-9c04-68999a5dd34e.png)

C'est ce qui a du se faire, quand j'ai testé. C'est aussi ce que j'ai observé avec XDebug quand j'ai reproduit le scénario de monté en version avec plus d'attention.

Là où les choses dégénèrent c'est quand la table est recréé. Il semblerait que le `drop_table` de la ligne 253 qui est exécuté, n'aille pas jusqu'au bout (en tous cas dans ce contexte), car le `create_table` suivant plante, ce qui empêche leur re-création et les fait disparaitre : 

> "Tablespace for table '`moodle`.`mdl_tool_attestoodle_user_style`' exists. Please DISCARD the tablespace before IMPORT."
> 
> DDL sql execution error
> 
> More information about this error
> Debug info: Tablespace for table '`moodle`.`mdl_tool_attestoodle_user_style`' exists. Please DISCARD the tablespace before IMPORT.
> CREATE TABLE mdl_tool_attestoodle_user_style (
> id BIGINT(10) NOT NULL auto_increment,
> userid BIGINT(10),
> trainingid BIGINT(10),
> templateid BIGINT(10),
> grpcriteria1 VARCHAR(35) COLLATE utf8mb4_unicode_ci,
> grpcriteria2 VARCHAR(35) COLLATE utf8mb4_unicode_ci,
> enablecertificate TINYINT(1),
> withdateformat VARCHAR(127) COLLATE utf8mb4_unicode_ci,
> CONSTRAINT PRIMARY KEY (id)
> )
> ENGINE = InnoDB
> DEFAULT COLLATE = utf8mb4_unicode_ci ROW_FORMAT=Compressed
> Error code: ddlexecuteerror
> Stack trace:
> 
>     line 492 of /lib/dml/moodle_database.php: ddl_change_structure_exception thrown
>     line 1070 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
>     line 77 of /lib/ddl/database_manager.php: call to mysqli_native_moodle_database->change_database_structure()
>     line 444 of /lib/ddl/database_manager.php: call to database_manager->execute_sql_arr()
>     line 255 of /admin/tool/attestoodle/db/upgrade.php: call to database_manager->create_table()
>     line 185 of /admin/tool/attestoodle/db/upgrade.php: call to create_table_learner_template()
>     line 632 of /lib/upgradelib.php: call to xmldb_tool_attestoodle_upgrade()
>     line 1857 of /lib/upgradelib.php: call to upgrade_plugins()
>     line 694 of /admin/index.php: call to upgrade_noncore()

En reprenant la même procédure, mais en prenant soin de supprimer le dossier /var/lib/mysql du serveur de BD avant d'extraire l'archive .tar, je retrouve mes 2 tables après l'upgrade, comme attendu.

Le seul soucis éventuel est donc peut-être un problème quand l'upgrade essait de créer une table qui existerait déjà. Ce qui normalement ne devrait pas se produire et que je n'ai pas réessayé.

**Problème 3 (le plus embêtant)**
Visiblement le bug tel qu'il s'est manifesté à moi (voir copie d'écran dans le commentaire initial de cette issue) a été corrigé dans le commit 16931df, dans la branche **develop** donc. Cela signifie que la branche master actuel est buggée.
Je suis passé sur la branche develop (commit 7c37da3) et je n'ai plus le problème.

Je reprendrai la résolution de ces problèmes demain. Il faudra faire un bug fix pour le problème n° 1 dans la branche develop (et le tester spécifiquement avec la même montée en version que celle que j'ai réalisé), puis merger develop avec master pour avoir une branche master de nouveau fonctionnelle (ce qui devrait toujours être le cas).

**Comment by dcadiou** [comment]
Problème principal (n°3) corrigé sur master (commit 72a61e9) 

_(in english : main problem fixed on master branch with commit 72a61e9)_
