### ISSUE TITLE
Table mdl_tool_attestoodle_tmp absente après un upgrade

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#89]
En faisant une montée en version du plugin Attestoodle du commit 05c4545 (version 2019010901) au dernier commit sur master, e075977 (version 2019043001), j'ai pu observé l'absence de cette table qui aurait du pourtant exister.

Cela provoque l'erreur suivante quand on essait de générer une attestation : 
![image](https://user-images.githubusercontent.com/25685520/58499105-bb9d7900-817f-11e9-8bc8-eb6872e12a5e.png)

_(in english : 
When upgrading from commit 05c4545, table mdl_tool_attestoodle_tmp is not created as expected)_

**Comment by dcadiou** [comment]
La création de cette table, en cas d'upgrade, est conditionnée au fait que la version courante ('2019010901' dans mon cas) est < '2018122601'. Ce qui n'est pas le cas dans le commit 05c4545.

Dans ce commit, la table tmp n'est pas encore utilisée, par contre elle l'est dans tous les suivants. Or, la condition décrite ci-avant, fait qu'un upgrade depuis ce commit (et tous ceux qui partagent la même version) ne déclenche pas (à tord) la création de la table tmp. Une fois upgradée la base ne contient pas la table.

![image](https://user-images.githubusercontent.com/25685520/58497259-da017580-817b-11e9-9ef5-adbbe6c5da84.png)

Je pense (à tester avec un upgrade depuis le commit 05c4545) que la condition suivante permettrait de faire mon upgrade en prod et de récupérer cette table : 
```
    if ($oldversion <= 2019010901) {
```

Par contre cela pourrait poser des problèmes à quiconque voudrait faire un upgrade depuis un commit entre f407be2 et 0c376a8. L'upgrade essaierait alors de créer la table tmp alors qu'elle existe déjà (décrite dans `install.xml`)

**Comment by mleconte** [comment]
La table tmp, ne contient que des données temporaires, elle est utilisée pour stocker les données nécessaires à la génération des attestations. Lors de la génération des attestations, la création du pdf et le traitement de l'image de fond prend le plus de temps, les données sont donc préparées puis stockées dans la table temp et à chaque génération d'attestation les données sont supprimées de cette table.

**Comment by dcadiou** [comment]
Merci Marc pour ces précisions.
Pour éviter d'impacter inutilement les commits entre f407be2 et 0c376a8, je ne vais pas corriger `db/upgrade.php`. En revanche, je vais modifier la version en base avant de faire l'upgrade, de sorte que la création de la table `tmp` se fasse.

Je vais donc exécuter la requête suivante sur ma prod, avant de faire la mise à jour : 
```sql
update mdl_config_plugins
set value = 2018122600
where plugin  = 'tool_attestoodle'
	and name = 'version'
;
```
