### ISSUE TITLE
Rendre la sélection des learners plus rapide à réaliser

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#91]
Dès qu'une formation inclue un grand nombre d'étudiants ayant besoin d'attestations, la sélection de ces étudiants est fastidieuse, car : 

- la pagination dans le formulaire de sélection des learners (`classes/training/select_learners.php`) est de 5 (en tous cas sur notre prod à Caen), ce qui éparpille l'info sur de trop nombreuses pages.
- il n'y a pas de moyen (ou alors je n'ai pas compris) de sélectionner des étudiants en masse.

Par ailleurs, je n'ai pas trouvé de documentation de cette partie dans le wiki. Je m'attendais à touver ça dans une page accessible depuis https://github.com/grp-attestoodle/moodle-tool_attestoodle/wiki/pedagogical_manager et https://github.com/grp-attestoodle/moodle-tool_attestoodle/wiki/personnel-administratif.

A un moment, j'ai cru que le bouton [exclude selection] permettait de sélectionner tous les étudiants, sauf ceux sélectionnés, mais visiblement ce n'est pas le cas. ça aurait pu être un moyen rapide de sélectionner un grand nombre d'étudiants quand la majorité d'une promo a besoin d'attest. Un bouton genre [tout sélectionner] pourrait aussi être utile.

Quand je vais faire la mise à jour en production (le dernier report la place mardi prochain), les 3 équipes de Caen qui utilisent Attestoodle vont devoir ajouter un grand nombre de learners à leurs formations. Sans quoi Attestoodle est inutilisable. Je devrais aussi leur expliquer comment le faire, mais je ne suis pas sur de connaitre la méthode la plus efficace et je ne peux pas les renvoyer vers de la doc.

Bref, j'ai besoin d'explications, voire que les demandes ci-dessus soient prises en compte s'il se confirme qu'elles sont pertinentes.

_(in english : the learner management form is missing ergonomics (pagination by 5 items, purpose of buttons difficult to understand. Additionnaly, it seems :_
_* to be impossible to unselect every learners (at least 1 learner is still selected)_
_* when visiting the learner form for the first time, it select all learners even if none has been expressly selected)_

**Comment by dcadiou** [comment]
Je viens de comprendre que dans la rubrique 'learner' de la page de configuration de la formation, il n'y a aucune indication du nombre de learners actuellement associés à la formation. Donc aucune indication ne dit pas qu'il n'y a pas de learners. Donc (n°2) [exclude learners] et [keep learner] font finalement bien ce que je m'attendais qu'ils fassent. 

En conséquence, mes demandes précédentes n'étaient pas pertinentes, donc je corrige avec une nouvelle demande, cette fois moins importante : 

- Il faudrait ajouter dans la page de configuration de la formation, dans la rubrique learners, le nombre de learners actuellement associés à la formation ou, au minimum une mention indiquant qu'il y en a. Sans quoi le comportement d'Attestoodle laisse penser que la sélection de learners a échoué. Comme moi, on peut alors s'acharner à essayer d'ajouter des learners sans finalement aller voir le rapport global et les découvrir.

Peut-être aussi ajouter un bouton [terminer] dans la page de sélection des learners. Pour l'instant j'utilise le fil d'Arianne pour revenir à la page de config, mais je ne suis pas sur que tout le monde y pensera.

**Comment by dcadiou** [comment]
J'ai utilisé un peu plus les nouvelles fonctionnalités de configuration d'une formation : il me semble que l'ergonomie et la cohérence pourraient être améliorées.

Pour l'instant, je vois les points suivants : 
* la rubrique 'Actions' n'est pas claire. Elle ne sert qu'à contenir des boutons. Ces derniers pourraient apparaitrent sans titre de rubrique ça éviterait cet intitulé qui apporte de la confusion.
* la rubrique 'Actions' devrait être à la fin (comme dans tous les formulaires Moodle)
* de prime abord on ne voit pas où générer des attestations or c'est ça qu'on "vend" avec attestoodle (c'est même dans le nom !). Le lien vers les rapports devrait : 
  * être intitulé 'rapport et attestations' (sinon comment savoir que c'est à partir de là qu'on a les attestations ?)
  * toujours s'afficher, mais désactivé s'il n'y a pas de learners pour que l'utilisateur sache que ce sera ici, mais qu'il manque quelque chose
  * le titre de la rubrique ne devrait pas se limiter à apprenant. Pourquoi pas 'les apprenants et leurs attestations' ou 'Apprenants et attestations'
* la rubrique sur les jalons sert maintenant à gérer les jalons, mais aussi à définir les cours qui constituent la formation. Il faudra que le titre de rubrique le laisse penser. Pourquoi ne pas l'intituler, par exemple, 'cours et jalons'.

En dépit de ces commentaires sur l'ergonomie, sur le fond, c'est beaucoup plus souple et va permettre de lever nombre de blocages que nous avions pour adresser des parcours de formation personnalisés. C'est du bon boulot.

**Comment by dcadiou** [comment]
J'ai oublié de préciser que j'ai repris les pages de wiki, notamment sur la configuration d'une formation. Je l'ai éclaté en sous-page dédiées. J'en ai, en particulier, créée une sur la gestion des apprenants (voir https://github.com/grp-attestoodle/moodle-tool_attestoodle/wiki/manage_learners) pour y expliquer ce que j'en ai compris. 
Il faudra probablement les compléter ou corriger ce qui doit l'être.

**Comment by dcadiou** [comment]
Je n'ai trouvé aucun moyen de supprimer tous les étudiants d'une formation. Il en reste toujours au moins un !

**Comment by dcadiou** [comment]
Autre problème : Quand je vais dans le formulaire de sélection des apprenants pour la première fois dans une formation, si je ne fais qu'ouvrir le formualire et rien d'autre (aucune sélection et encore moins de validation), quand je reviens sur la page de configuration de la formation, le bouton [Rapport global de la formation] est affiché. Si je clic dessus, je constate que tous les apprenants possibles ont été associés à la formation, **alors que je ne l'ai pas demandé** (et normalement c'est qui le chef ?!).

**Comment by dcadiou** [comment]
J'ajoute un point d'ergonomie : à chaque clic sur une coche de sélection, du code s'exécute, ce qui rend l'interface moins réactive. Ne serait-il pas possible de pouvoir sélectionner un ensemble d'étudiants, puis de cliquer sur un bouton de validation, qui déclencherait ce code une fois pour toute la sélection ?

**Comment by mleconte** [comment]
Réglé par le commit 0d34a3a
Ajax complexifie le code aussi je n'en place que lorsque cela est obligatoire (exemple génération des attestation en bloc)
