### ISSUE TITLE
Caractères accentués mal gérés dans filtrage des activités dans le formulaire de gestion des jalons

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#92]
Dans le formulaire de gestion des jalons, quand on saisie un mot accentué dans le champ _name_ de filtrage des activité, une fois le bouton [filtrer] cliqué, le mot saisie est remplacé par un mot sans accent. 

Exemple, avant de cliquer [filtrer] : 

![image](https://user-images.githubusercontent.com/25685520/58861722-4c5be380-86af-11e9-8058-7d44c1903d77.png)

Après : 

![image](https://user-images.githubusercontent.com/25685520/58861772-68f81b80-86af-11e9-8883-4464e683680b.png)

_(in english : in the milestones management page, in the filtering form, when a word with specific caracters (such as French caracters) is typed, after validation (clic on [filter] button), the typed word is replaced by the same word but without those caracters)_

**Comment by cemu-guillaumegirard** [comment]
Même constat pour les caractères spéciaux (testé avec un underscore) et les chiffres

**Comment by mleconte** [comment]
Corrigé par le commit 32f3c02 version 1.7.1
