### ISSUE TITLE
Rendre la rubrique Apprenants accessible, même si aucun jalon n'a encore été définis.

### ISSUE THREAD

**Issue by dcadiou** [grp-attestoodle/moodle-tool_attestoodle#93]
Dans la page de configuration d'une formation, si aucun jalon n'a encore été défini, la rubrique _Apprenants_ ne s'affiche pas.

C'est embêtant pour le personnel administratif qui pourraient être amené à renseigner quels étudiants vont avoir besoin d'attestations, avant même que les équipes pédagogiques n'aient eu le temps de définir les jalons.

Le fait de sélectionner les apprenants d'une formation est un travail supplémentaire demandé aux scolarités ou aux enseignants, conditionner cette saisie au renseignement préalable des jalons (opération délicate qui mérite un sérieux travail de conception pédagogique potentiellement long à réaliser), me parait une contrainte inutile.

Est-il possible de lever cette condition ?

**Comment by dcadiou** [comment]
Plus globalement, bien que la génération d'attestations soit la fonctionnalité principale d'Attestoodle, elle est de plus en plus difficile à atteindre.

En effet, 
* elle se trouve dans la page _Rapport global de la formation_ (ce qui ne dit pas que c'est là qu'on génère des attestations),
* elle-même accessible que par la rubrique _Apprenants_ (ce titre ne dit pas non plus que cela concerne les attestations) de la page de configuration de la formation,
* elle-même accessible que si des jalons ont été définits (condition qui ne va pas de soi)

Je sais que ce problème n'est pas nouveau. Dès les 1ère versions c'était déjà le cas, mais avec les derniers changements c'est pire.

Je propose que dans la page de gestion de la formation, il y ait une rubrique spécifique "Rapports et Attestations" dissociée de la rubrique _Apprenants_, qui permettent d'accéder au rapport global. Le bouton [Rapport global] pourrait être renommé, lui aussi, _Rapport et Attestations_. Ce bouton pourrait être dévalidé s'il n'y a pas d'Apprenants ou de jalons, mais il resterait visible.

**Comment by mleconte** [comment]
Désolé cela n'est pas possible, seul les apprenants inscrits à un cours possédant au moins un jalons sont récupérés. Les apprenants de la catégorie ne sont plus systématiquement concernés par la formation. On peut imaginer une catégorie nommée 'formation' qui n'existe que pour porter des formations. Cette catégorie pourrait ne porter aucun cours, donc nous n'aurions aucun apprenant !
C'est donc obligatoirement qu'après la déclaration des jalons qu'il est possible d'obtenir les potentiels apprenant .
