### ISSUE TITLE
[Temps total formation] Incohérence pages "Paramètres" et "Gestion jalons"

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#97]
Je suis sur le serveur de démo et j'ai une incohérence entre le temps total de la formation affiché sur la page "Paramètres" de la formation et la page "Gestion des jalons" de cette même formation. 

**Page paramètres : temps total 100h00**
![issue_incoherence_temps_totaux_01](https://user-images.githubusercontent.com/31622244/58964974-0fc3e100-87b0-11e9-80a2-721c4aefbf72.png)

**Page gestion des jalons : temps total 79h00**
![issue_incoherence_temps_totaux_02](https://user-images.githubusercontent.com/31622244/58964984-13576800-87b0-11e9-826f-82fbe7bca160.png)

Lorsque je modifie un jalon le temps total est actualisé correctement sur les deux totaux : admettons que j'enlève 1h, sur paramètre ça passe de 100h à 99h et sur gestions des jalons ça passe de 79h à 78h.

_NB : il s'agit d'une formation qui avait déjà des jalons avant la mise à jour vers la version 1.4.4 du plug-in_

**Comment by cemu-guillaumegirard** [comment]
Sur une autre formation j'ai pu modifier des jalons sans que cette incohérence n'apparaisse

(Je n'ai pas le temps d'investiguer plus en profondeur pour le moment alors je mets ici les informations brut de décoffrage)

**Comment by cemu-guillaumegirard** [comment]
La purge des caches n'a rien donné

**Comment by mleconte** [comment]
Ce problème provient que des jalons ont été définit sur des activités sans suivi d'achèvement, cela était possible avant le changement de version.
Lorsqu'on rétablit l'achèvement les temps sont correctes.
Si cela se reproduit on pourra envisager un traitement correctif pour forcer l'achèvement ou supprimer les jalons sans achèvement.
Pour le reproduire il faut déclarer un jalons puis supprimer l'achèvement d'activité.
