### ISSUE TITLE
[Paramètres] Ajouter une validation pour la suppression d'une formation

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#98]
Lorsque l'on clique sur le bouton "Supprimer" de la page de paramètres d'une formation, la formation est supprimée sans validation, ce qui pourrait causer des problèmes de suppression accidentelle.

Il serait bon de rajouter une validation simple genre popup-up rouge "Êtes-vous sûr de vouloir supprimer la formation bidule ? Oui - Non"

**Comment by mleconte** [comment]
Réalisé cf commit de5d50b
