### ISSUE TITLE
[CSS] Résidus de vieilles versions

### ISSUE THREAD

**Issue by cemu-guillaumegirard** [grp-attestoodle/moodle-tool_attestoodle#99]
Il doit rester des résidus des premières versions dans le CSS du plug-in car j'ai ceci qui s'affiche :

![issue_residus_CSS](https://user-images.githubusercontent.com/31622244/58967509-9bd80780-87b4-11e9-9aee-a345a0a011be.png)

_NB : le temps jalons affiché est celui qui se trouve dans le `span class="tps_jalon"`_

**Comment by mleconte** [comment]
Traité cf commit fb73115
